SHELL := /bin/bash

# Default to `go` on PATH; override with `make GO=/path/to/go` if needed.
# Includes a common fallback for environments where Go is installed under $HOME/go/bin.
GO ?= $(shell command -v go 2>/dev/null || echo $$HOME/go/bin/go)

.PHONY: build sync-skills verify-skills

# Source for a throwaway helper binary used only by verify-skills (see
# that target's comment for why it exists). Written to a temp file with
# $(file ...) and run via `go run` — never installed, never committed.
define DUMPSKILLS_GO_SRC
package main

import (
	"fmt"
	"os"

	"github.com/ddwht/parlay/core/internal/embedded"
)

func main() {
	skills, err := embedded.ReadAllSkills()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	for _, s := range skills {
		fmt.Printf("===DUMPSKILL:%s===\n", s.Name)
		fmt.Print(string(s.Content))
	}
}
endef

# Build the parlay binary from current source.
# CGO is disabled: parlay has no cgo dependencies, so a pure-Go build is
# faster and works in environments without a C toolchain.
build:
	CGO_ENABLED=0 $(GO) build -o parlay ./core/cmd/parlay
	CGO_ENABLED=0 $(GO) build -o parlay-studio ./studio/cmd/parlay-studio

# Edit-source -> build -> upgrade, in one shot.
# Use this after changing anything under core/internal/embedded/{skills,schemas}/.
# This is the dogfooding rule documented in CLAUDE.md.
sync-skills: build
	./parlay upgrade

# Verify deployed skills and schemas are in sync with the embedded source.
# Expected differences: deployer-added frontmatter and trailing whitespace.
# Anything else means someone edited a deployed copy directly (which is forbidden)
# OR the source was edited but `make sync-skills` was not run (also forbidden).
#
# Skill sources now carry their own frontmatter (parsed by
# embedded.ReadAllSkills as the description single-source) AND may
# contain deploy-time-expansion markers (`<!-- parlay:expand-... -->`)
# that ReadAllSkills expands into canonical prose before any deployer
# sees it — see core/internal/embedded/skills.go. That expansion is
# Go-side string substitution; reimplementing it in shell would just
# create a second, driftable copy of the expansion text right here.
# Instead we shell out to `go run` on a throwaway program that calls
# ReadAllSkills() directly, so the "expected body" side of this diff is
# always generated by the SAME code deployers actually run — no
# duplicated expansion logic to keep in sync.
verify-skills: $(shell mkdir -p core/internal/embedded/cmd/dumpskills-verify-tmp)$(file >core/internal/embedded/cmd/dumpskills-verify-tmp/main.go,$(DUMPSKILLS_GO_SRC))
	@drift=0; \
	tmpdir=$$(mktemp -d); \
	trap 'rm -rf "$$tmpdir"; rm -rf core/internal/embedded/cmd/dumpskills-verify-tmp' EXIT; \
	$(GO) run ./core/internal/embedded/cmd/dumpskills-verify-tmp > "$$tmpdir/expanded-all.txt" 2>"$$tmpdir/dump.err" \
		|| { echo "verify-skills: failed to run dump helper:"; cat "$$tmpdir/dump.err"; exit 1; }; \
	awk -v outdir="$$tmpdir" '/^===DUMPSKILL:/{if(f)close(f); name=$$0; sub(/^===DUMPSKILL:/,"",name); sub(/===$$/,"",name); f=outdir"/expanded."name".txt"; next} {print > f}' "$$tmpdir/expanded-all.txt"; \
	for src in core/internal/embedded/skills/*.skill.md; do \
		name=$$(basename $$src .skill.md); \
		dst=".claude/skills/parlay-$$name/SKILL.md"; \
		expanded="$$tmpdir/expanded.$$name.txt"; \
		if [ ! -f "$$dst" ]; then \
			echo "MISSING:  $$dst (run 'make sync-skills')"; \
			drift=1; \
			continue; \
		fi; \
		if [ ! -f "$$expanded" ]; then \
			echo "ERROR:    dump helper produced no output for skill $$name"; \
			drift=1; \
			continue; \
		fi; \
		body_diff=$$(diff <(awk 'BEGIN{fm=0;done=0} NR==1 && /^---$$/ {fm=1; next} fm && /^---$$/ {fm=0; done=1; next} fm {next} done && /^$$/ {done=0; next} {done=0; print}' $$dst | sed 's/[[:space:]]*$$//') <(sed 's/[[:space:]]*$$//' "$$expanded") || true); \
		if [ -n "$$body_diff" ]; then \
			echo "DRIFT:    $$dst differs from $$src (post-frontmatter-strip, post-marker-expansion)"; \
			drift=1; \
		fi; \
	done; \
	for src in core/internal/embedded/schemas/*.schema.md; do \
		name=$$(basename $$src); \
		dst=".parlay/schemas/$$name"; \
		if [ ! -f "$$dst" ]; then \
			echo "MISSING:  $$dst (run 'make sync-skills')"; \
			drift=1; \
			continue; \
		fi; \
		if ! diff -q <(sed 's/[[:space:]]*$$//' $$src) <(sed 's/[[:space:]]*$$//' $$dst) >/dev/null; then \
			echo "DRIFT:    $$dst differs from $$src"; \
			drift=1; \
		fi; \
	done; \
	if [ $$drift -eq 0 ]; then \
		echo "OK: skills and schemas are in sync with the embedded source."; \
	else \
		exit 1; \
	fi
