// parlay-feature: parlay-tool/page-assembly-derivation
// parlay-component: assembly-projection
//
// The one derivation that defines what a page's assembly suite MUST contain.
//
// testcases.schema.md says the per-page assembly suite is "generated by
// build-feature with no author in the loop ... it carries no hand-authored
// expectations", while the v3 contract says every case carries
// `criterion: {ref, text}` and makes its absence an error. Those two
// statements cannot both be satisfied, so build-feature emitted an illegal
// file every time: 11 of 11 archived builds across four releases either
// omitted the criterion, stamped `coverage: state-only`, or cited a criterion
// the case does not discharge. The citations, when present, were wrong 7 times
// out of 7 — a case asserting that four components mounted, citing a criterion
// about which columns a table shows.
//
// The resolution is that an assembly assertion DISCHARGES NOTHING. "This
// component reached the renderer" is not the acceptance of any contract
// criterion, and there is no fragment criterion for which it is the evidence.
// So assembly cases carry a machine identity instead of a citation, and are
// excluded from criterion coverage rather than pretending to satisfy it.
//
// This file is the single source of that truth. The emitter serializes what it
// returns; the validator recomputes it and diffs. Two implementations would
// reintroduce the disagreement one level up — a validator that rejects what the
// emitter writes — so there is exactly one, and both callers hold it.
package agent

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/ddwht/parlay/core/internal/parser"
)

// Assembly assertion kinds. Closed set: the three facts a page manifest plus a
// surface can state about composition without inventing anything.
const (
	// AssertMounted — the component this page declares reaches the renderer.
	AssertMounted = "mounted"
	// AssertHitReachable — a component carrying actions: can receive input.
	AssertHitReachable = "hit-reachable"
	// AssertNotHitReachable — a fragment marked interactive: false is emitted
	// as non-hit-testable output, so the "dead mouse" defect is impossible
	// rather than merely visible.
	AssertNotHitReachable = "not-hit-reachable"
)

// Capability terms an adapter must declare for an assertion to be executable.
//
// CapHitTesting is deliberately NOT one of render-support's levels. That field
// is the closed set {mounted, output, content} and has no vocabulary for
// pointer reachability at all — so before this term existed, two of the three
// assembly assertion kinds were not merely unsupported but INEXPRESSIBLE: no
// adapter could declare them however much it could do. Folding hit-testing
// into `mounted` would have been worse than leaving it out, because it would
// let "I can see a mount point" stand in as proof of "a pointer can reach it".
const (
	CapRenderMounted = "mounted"
	CapHitTesting    = "hit-testing"
)

// AssemblyAssertion is one derived composition fact.
//
// It carries no criterion and never will. Identity is (Page, Subject, Kind) —
// the triple the duplicate walker keys on, so a case cannot evade detection by
// being renamed or having its steps reordered.
type AssemblyAssertion struct {
	Page    string
	Subject string
	Kind    string
	// Ref is the fragment this assertion was derived from, for diagnostics and
	// for the retirement join. Not part of identity: two fragments cannot
	// occupy one slot on one page after supersession resolves.
	Ref string
	// RequiredCapability is what an adapter must declare to make this
	// assertion runnable.
	RequiredCapability string
}

// ID is the canonical identity used for diffing and duplicate detection.
func (a AssemblyAssertion) ID() string {
	return fmt.Sprintf("%s|%s|%s", a.Page, a.Subject, a.Kind)
}

// AssemblyStep is one executable step of a derived case.
//
// Expected is a STRING, not a bool. Real testcases files carry `expected:`
// values like `disabled` and `rejected` alongside `true`, so a bool field
// refused to parse the very files this validates — and because an unparseable
// testcases file is now a blocker rather than a shrug, that would have failed
// closed on correct input. It is compared as text either way.
type AssemblyStep struct {
	Action   string `yaml:"action,omitempty" json:"action,omitempty"`
	Verify   string `yaml:"verify,omitempty" json:"verify,omitempty"`
	Target   string `yaml:"target" json:"target"`
	Value    string `yaml:"value,omitempty" json:"value,omitempty"`
	Expected string `yaml:"-" json:"expected,omitempty"`
}

// MarshalYAML emits `expected:` as an untagged scalar, so a derived step
// writes `expected: true` rather than the quoted `expected: "true"` a plain
// string field would produce — the runner distinguishes the two.
func (s AssemblyStep) MarshalYAML() (interface{}, error) {
	m := &yaml.Node{Kind: yaml.MappingNode}
	add := func(k, v string, style yaml.Style) {
		m.Content = append(m.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: k},
			&yaml.Node{Kind: yaml.ScalarNode, Value: v, Style: style})
	}
	if s.Action != "" {
		add("action", s.Action, 0)
	}
	if s.Verify != "" {
		add("verify", s.Verify, 0)
	}
	add("target", s.Target, 0)
	if s.Value != "" {
		add("value", s.Value, 0)
	}
	if s.Expected != "" {
		add("expected", s.Expected, 0)
	}
	return m, nil
}

// Steps returns the canonical mechanics for this assertion.
//
// These are DERIVED, not chosen. Identity alone — (page, subject, assertion) —
// was not enough to police: a case carrying the right derivation: block and
// empty or unrelated steps satisfied every identity check while asserting
// nothing, which is the false-citation failure rebuilt as a true label over a
// false test. So the derivation owns the mechanics too, and the validator
// diffs them.
//
// Every verb is inside the schema's closed vocabulary — actions
// {render, click, input, select, navigate, wait, appears} and verifications
// {element, state, route, count, text, visible, hidden, enabled, disabled}.
// No route is invented: `render` targets the component directly rather than
// navigating to a path the derivation would have to guess.
func (a AssemblyAssertion) Steps() []AssemblyStep {
	render := AssemblyStep{Action: "render", Target: a.Subject}
	switch a.Kind {
	case AssertMounted:
		return []AssemblyStep{render, {Action: "appears", Target: a.Subject, Value: "mounted"}}
	case AssertHitReachable:
		return []AssemblyStep{render, {Verify: "enabled", Target: a.Subject, Expected: "true"}}
	case AssertNotHitReachable:
		// interactive: false means the adapter emits this as non-hit-testable
		// output. `disabled` is the closest assertion the closed vocabulary
		// carries; it is the claim that input cannot reach the component.
		return []AssemblyStep{render, {Verify: "disabled", Target: a.Subject, Expected: "true"}}
	}
	return nil
}

// StepFingerprint is the canonical form the validator compares, so
// reindentation and key reordering do not read as a changed mechanism while a
// changed target or verb does.
func (a AssemblyAssertion) StepFingerprint() string {
	return FingerprintSteps(a.Steps())
}

// FingerprintSteps canonicalizes any step list onto the same form.
func FingerprintSteps(steps []AssemblyStep) string {
	var b strings.Builder
	for _, s := range steps {
		exp := strings.TrimSpace(s.Expected)
		fmt.Fprintf(&b, "%s/%s/%s/%s/%s;",
			strings.TrimSpace(s.Action), strings.TrimSpace(s.Verify),
			strings.TrimSpace(s.Target), strings.TrimSpace(s.Value), exp)
	}
	return b.String()
}

// AssemblySuite is the derived suite for one page, already split by whether
// the adapter can execute each assertion.
type AssemblySuite struct {
	Page string
	// Supported assertions become real cases.
	Supported []AssemblyAssertion
	// Pending assertions are capability DEBT, recorded explicitly. They are
	// not `coverage: state-only` — that field means a contract criterion was
	// observed weakly, which requires a human judgment about a weakening. A
	// composition fact the adapter cannot assert yet is not a weakened
	// observation of anything; calling it one manufactured an unapprovable
	// blocker with an empty criterion, which is precisely how the tool talked
	// itself into a state no human could discharge.
	Pending []AssemblyAssertion
}

// AdapterCapabilities is what the projection needs to know about the target.
type AdapterCapabilities struct {
	// RenderSupport is the adapter's declared `render-support:` levels.
	RenderSupport map[string]bool
	// HitTesting reports whether the adapter declares it can assert pointer
	// reachability. Separate from RenderSupport by construction.
	HitTesting bool
}

// Supports reports whether the adapter can execute an assertion of this kind.
func (c AdapterCapabilities) Supports(capability string) bool {
	switch capability {
	case CapRenderMounted:
		return c.RenderSupport[CapRenderMounted]
	case CapHitTesting:
		return c.HitTesting
	}
	return false
}

// DeriveAssemblySuite computes the required assembly suite for one page from
// one feature's ACTIVE contribution.
//
// `active` must already be the resolved, page-filtered, owner-filtered set —
// see ResolveActiveView. Passing unresolved fragments would derive a mount
// assertion for a component supersession has retired, which is the defect the
// resolver exists to remove.
//
// Deterministic: assertions come back sorted by identity, so the emitter's
// output and the validator's expectation are byte-comparable.
func DeriveAssemblySuite(page string, active []parser.Fragment, caps AdapterCapabilities) AssemblySuite {
	suite := AssemblySuite{Page: page}

	var all []AssemblyAssertion
	for _, f := range active {
		subject := parser.Slugify(f.Name)
		ref := FragmentRef(f)

		// Every declared component asserts it reaches the renderer.
		all = append(all, AssemblyAssertion{
			Page: page, Subject: subject, Kind: AssertMounted, Ref: ref,
			RequiredCapability: CapRenderMounted,
		})

		// interactive: false is a positive claim that the adapter emits this
		// as non-hit-testable output — the assertion is that input CANNOT
		// reach it. It is not the absence of the hit-reachable assertion.
		if !f.IsInteractive() {
			all = append(all, AssemblyAssertion{
				Page: page, Subject: subject, Kind: AssertNotHitReachable, Ref: ref,
				RequiredCapability: CapHitTesting,
			})
			continue
		}

		// A component carrying actions: can receive input.
		if strings.TrimSpace(f.Actions) != "" {
			all = append(all, AssemblyAssertion{
				Page: page, Subject: subject, Kind: AssertHitReachable, Ref: ref,
				RequiredCapability: CapHitTesting,
			})
		}
	}

	sort.Slice(all, func(i, j int) bool { return all[i].ID() < all[j].ID() })

	for _, a := range all {
		if caps.Supports(a.RequiredCapability) {
			suite.Supported = append(suite.Supported, a)
			continue
		}
		suite.Pending = append(suite.Pending, a)
	}
	return suite
}

// AssemblyPagesFor lists the pages a feature actively contributes to, sorted.
func AssemblyPagesFor(active []parser.Fragment) []string {
	seen := map[string]bool{}
	for _, f := range active {
		if strings.TrimSpace(f.Page) != "" {
			seen[f.Page] = true
		}
	}
	out := make([]string, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}
